name: gamebox_plugin
description: A new Flutter plugin for gamebox  extend developed.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  geolocator_android: ^3.0.4
  flutter_localizations: # 多言語
    sdk: flutter

  dio: ^4.0.6
  http: ^0.13.0

  path: ^1.8.2

  #  暂不可升级
  get: ^4.3.8
  decimal: ^1.5.0
  dartdoc: ^6.2.0


  path_provider: ^2.0.11

  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+3
  flutter_svg: ^1.0.3
  # Business related
  in_app_purchase: ^2.0.1
  crypto: ^3.0.2
  # notification
  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  responsive_framework: ^0.1.8


  html: ^0.15.0
  #  card_swiper: ^2.0.3
  percent_indicator: ^4.2.2
  flutter_screenutil: ^5.5.2
  rubber: ^1.0.1
  flexible_calendar: ^1.0.1
  flutter_switch: ^0.3.2
  preload_page_view: ^0.1.6
  group_button: ^5.0.1
  o_popup: ^1.0.1
  webview_flutter: ^3.0.4
  image_cacheing: ^0.0.2
  flutter_easyloading: ^3.0.3
  #  share_plus: 6.3.1
  ndialog: ^4.1.1
  url_launcher: ^6.1.0
  url_launcher_ios: ^6.0.13
  expansion_tile_card: ^2.0.0
  provider: ^6.0.2
  flustars: ^2.0.1
  sp_util: ^2.0.3
  octo_image: ^1.0.1
  cached_network_image: ^3.2.0
  sensors_plus: ^2.0.2
  event_bus: ^2.0.0
  connectivity_plus: ^3.0.3
  sleek_circular_slider: ^2.0.1
  package_info_plus: ^3.0.3
  flutter_advanced_switch: ^3.0.1
  advanced_search: ^2.2.3
  encrypt: ^5.0.1
  asn1lib: ^1.1.0
  args: ^2.3.1
  clock: ^1.1.0
  collection: ^1.16.0
  pointycastle: ^3.6.0
  molten_navigationbar_flutter: ^1.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_pie_chart: ^0.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  r_dotted_line_border: ^0.1.1
  intl: ^0.17.0
  need_resume: ^1.0.6
  back_button_interceptor: ^6.0.0
  isolate_downloader: ^1.0.4
  ele_progress: ^0.0.1
  #  fluwx: 3.8.5
  umeng_common_sdk: ^1.2.4
  image_picker: ^0.8.5+3
  image_picker_ios: ^0.8.5+3
  flutter_keyboard_visibility: ^5.2.0
  geolocator_apple: ^2.0.0+2
  webview_flutter_wkwebview: ^2.7.0
  #TODO：Game_Box:一键登录、第三方微信、QQ登录
  rongcloud_im_wrapper_plugin: ^5.3.3
  adobe_xd: ^2.0.1
  velocity_x: ^3.6.0
  extended_nested_scroll_view: ^6.0.0
  ff_annotation_route_library: ^3.0.0
  loading_more_list: ^5.0.3
  flutter_riverpod: ^2.3.5
  hooks_riverpod: ^2.3.5
  charts_flutter: ^0.12.0
  geolocator: ^8.0.1
  fluttertoast: ^8.2.1
  mobcommonlib: ^1.1.4
  mobsms: ^1.1.8
  tobias: ^2.4.1+1
  flutter_easyrefresh: ^2.2.2
  f_verification_box: ^0.0.2
  loading_indicator: ^3.1.0
  flutter_screenshot_callback: ^0.0.8
  card_swiper: ^2.0.4
  flutter_hooks: ^0.18.6
  easy_permission: ^1.0.0
  progress_tab_bar: ^0.1.7
  flutter_native_splash: ^2.2.19
  in_app_purchase_android: ^0.2.5
  app_tracking_transparency: ^2.0.3
  flutter_spinkit: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.gamebox_plugin
        pluginClass: GameboxPlugin
      ios:
        pluginClass: GameboxPlugin
  assets:
    - assets/gamebox/
    - assets/vmos_cloud.db

  fonts:
    - family: Source Han Sans CN
      fonts:
        - asset: assets/fonts/Source Han Sans CN.ttf
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
